spring:
  datasource:
    url: jdbc:mysql://localhost:3307/gym_management
    username: root
    password: K@psodia8504
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
     hibernate:
        ddl-auto: update

